<a href="https://colab.research.google.com/github/raju1207/Deeplearning-Analysis/blob/main/Retail_sales_forcast.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_sales = pd.read_csv("sales_data_set.csv")
df_stores = pd.read_csv("stores_data_set.csv")
df_features = pd.read_csv("Features_data_set.csv")

In [3]:
df_sales.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday
0      1     1  05/02/2010      24924.50      False
1      1     1  12/02/2010      46039.49       True
2      1     1  19/02/2010      41595.55      False
3      1     1  26/02/2010      19403.54      False
4      1     1  05/03/2010      21827.90      False

In [4]:
df_features.head()

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False
1,1,12/02/2010,38.51,2.548,NaN,NaN,NaN,NaN,NaN,211.242170,8.106,True
2,1,19/02/2010,39.93,2.514,NaN,NaN,NaN,NaN,NaN,211.289143,8.106,False
3,1,26/02/2010,46.63,2.561,NaN,NaN,NaN,NaN,NaN,211.319643,8.106,False
4,1,05/03/2010,46.50,2.625,NaN,NaN,NaN,NaN,NaN,211.350143,8.106,False

In [5]:
df_stores.head()

   Store Type    Size
0      1    A  151315
1      2    A  202307
2      3    B   37392
3      4    A  205863
4      5    B   34875

In [6]:
df_store_sales=pd.merge(df_sales,df_stores,on="Store")

In [7]:
df_store_sales.head()

   Store  Dept        Date  Weekly_Sales  IsHoliday Type    Size
0      1     1  05/02/2010      24924.50      False    A  151315
1      1     1  12/02/2010      46039.49       True    A  151315
2      1     1  19/02/2010      41595.55      False    A  151315
3      1     1  26/02/2010      19403.54      False    A  151315
4      1     1  05/03/2010      21827.90      False    A  151315

In [8]:
df_store_sales.shape

(421570, 7)

In [9]:
df_final = pd.merge(df_features,df_store_sales,on=["Store","Date"])

In [10]:
df_final

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_x,Dept,Weekly_Sales,IsHoliday_y,Type,Size
0,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,1,24924.50,False,A,151315
1,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,2,50605.27,False,A,151315
2,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,3,13740.12,False,A,151315
3,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,4,39954.04,False,A,151315
4,1,05/02/2010,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,5,32229.38,False,A,151315
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,False,B,118221
421566,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,False,B,118221
421567,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,False,B,118221
421568,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,False,B,118221
421569,45,26/10/2012,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,False,B,118221

In [11]:
df_final["Type"].unique()

array(['A', 'B', 'C'], dtype=object)

In [12]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 17 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Date          421570 non-null  object
 2   Temperature   421570 non-null  float64
 3   Fuel_Price    421570 non-null  float64
 4   MarkDown1     150681 non-null  float64
 5   MarkDown2     111248 non-null  float64
 6   MarkDown3     137091 non-null  float64
 7   MarkDown4     134967 non-null  float64
 8   MarkDown5     151432 non-null  float64
 9   CPI           421570 non-null  float64
 10  Unemployment  421570 non-null  float64
 11  IsHoliday_x   421570 non-null  bool
 12  Dept          421570 non-null  int64
 13  Weekly_Sales  421570 non-null  float64
 14  IsHoliday_y   421570 non-null  bool
 15  Type          421570 non-null  object
 16  Size          421570 non-null  int64
dtypes: bool(2), float64(10), int64(3), object(2)
memory usage: 49.0+ MB

In [13]:
df_final["Date"]=pd.to_datetime(df_final["Date"],format="%d/%m/%Y")

In [14]:
df_final["Week_of_year"]=df_final["Date"].dt.isocalendar().week

In [15]:
df_final

,Store,Date,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_x,Dept,Weekly_Sales,IsHoliday_y,Type,Size,Week_of_year
0,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,1,24924.50,False,A,151315,5
1,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,2,50605.27,False,A,151315,5
2,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,3,13740.12,False,A,151315,5
3,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,4,39954.04,False,A,151315,5
4,1,2010-02-05,42.31,2.572,NaN,NaN,NaN,NaN,NaN,211.096358,8.106,False,5,32229.38,False,A,151315,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,False,B,118221,43
421566,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,False,B,118221,43
421567,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,False,B,118221,43
421568,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,False,B,118221,43
421569,45,2012-10-26,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,False,B,118221,43

In [16]:
df_final=df_final.drop("Date",axis=1)

In [17]:
df_final.isnull().sum()

Store                0
Temperature          0
Fuel_Price           0
MarkDown1       270889
MarkDown2       310322
MarkDown3       284479
MarkDown4       286603
MarkDown5       270138
CPI                  0
Unemployment         0
IsHoliday_x          0
Dept                 0
Weekly_Sales         0
IsHoliday_y          0
Type                 0
Size                 0
Week_of_year         0
dtype: int64

In [18]:
df_final.fillna(0,inplace=True)

In [19]:
df_final.isnull().sum()

Store           0
Temperature     0
Fuel_Price      0
MarkDown1       0
MarkDown2       0
MarkDown3       0
MarkDown4       0
MarkDown5       0
CPI             0
Unemployment    0
IsHoliday_x     0
Dept            0
Weekly_Sales    0
IsHoliday_y     0
Type            0
Size            0
Week_of_year    0
dtype: int64

In [20]:
df_final

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday_x,Dept,Weekly_Sales,IsHoliday_y,Type,Size,Week_of_year
0,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,1,24924.50,False,A,151315,5
1,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,2,50605.27,False,A,151315,5
2,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,3,13740.12,False,A,151315,5
3,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,4,39954.04,False,A,151315,5
4,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,5,32229.38,False,A,151315,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,False,B,118221,43
421566,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,False,B,118221,43
421567,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,False,B,118221,43
421568,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,False,B,118221,43
421569,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,False,B,118221,43

In [21]:
df_final.drop("IsHoliday_y",axis=1,inplace=True)

In [22]:
df_final.rename(columns={"IsHoliday_x":"IsHoliday"},inplace=True)

In [23]:
df_final

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday,Dept,Weekly_Sales,Type,Size,Week_of_year
0,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,1,24924.50,A,151315,5
1,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,2,50605.27,A,151315,5
2,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,3,13740.12,A,151315,5
3,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,4,39954.04,A,151315,5
4,1,42.31,2.572,0.00,0.00,0.0,0.00,0.00,211.096358,8.106,False,5,32229.38,A,151315,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421565,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,93,2487.80,B,118221,43
421566,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,94,5203.31,B,118221,43
421567,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,95,56017.47,B,118221,43
421568,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,97,6817.48,B,118221,43
421569,45,58.85,3.882,4018.91,58.08,100.0,211.94,858.33,192.308899,8.667,False,98,1076.80,B,118221,43

In [24]:
df_final["IsHoliday"].unique()

array([False,  True])

In [25]:
df_final["Type"].unique()

array(['A', 'B', 'C'], dtype=object)

In [26]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Temperature   421570 non-null  float64
 2   Fuel_Price    421570 non-null  float64
 3   MarkDown1     421570 non-null  float64
 4   MarkDown2     421570 non-null  float64
 5   MarkDown3     421570 non-null  float64
 6   MarkDown4     421570 non-null  float64
 7   MarkDown5     421570 non-null  float64
 8   CPI           421570 non-null  float64
 9   Unemployment  421570 non-null  float64
 10  IsHoliday     421570 non-null  bool
 11  Dept          421570 non-null  int64
 12  Weekly_Sales  421570 non-null  float64
 13  Type          421570 non-null  object
 14  Size          421570 non-null  int64
 15  Week_of_year  421570 non-null  UInt32
dtypes: UInt32(1), bool(1), float64(10), int64(3), object(1)
memory usage: 47.4+ MB

In [27]:
df_final["IsHoliday"].map({"False":0,"True":1})
df_final["Type"].map({"A":0,"B":1,"C":2})

0         0
1         0
2         0
3         0
4         0
         ..
421565    1
421566    1
421567    1
421568    1
421569    1
Name: Type, Length: 421570, dtype: int64

In [28]:
from sklearn.preprocessing import OrdinalEncoder
encode=OrdinalEncoder()
df_final["IsHoliday"]=encode.fit_transform(df_final[["IsHoliday"]])
df_final["Type"]=encode.fit_transform(df_final[["Type"]])

In [29]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 16 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Temperature   421570 non-null  float64
 2   Fuel_Price    421570 non-null  float64
 3   MarkDown1     421570 non-null  float64
 4   MarkDown2     421570 non-null  float64
 5   MarkDown3     421570 non-null  float64
 6   MarkDown4     421570 non-null  float64
 7   MarkDown5     421570 non-null  float64
 8   CPI           421570 non-null  float64
 9   Unemployment  421570 non-null  float64
 10  IsHoliday     421570 non-null  float64
 11  Dept          421570 non-null  int64
 12  Weekly_Sales  421570 non-null  float64
 13  Type          421570 non-null  float64
 14  Size          421570 non-null  int64
 15  Week_of_year  421570 non-null  UInt32
dtypes: UInt32(1), float64(12), int64(3)
memory usage: 50.3 MB

In [30]:
df_final.duplicated().sum()

0

In [31]:
x=df_final.drop("Weekly_Sales",axis=1)
y=df_final["Weekly_Sales"]

In [32]:
df_final.corr()

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday,Dept,Weekly_Sales,Type,Size,Week_of_year
Store,1.000000,-0.050097,0.065290,-0.059844,-0.033829,-0.020331,-0.042724,-0.012452,-0.211088,0.208552,-0.000548,0.024004,-0.085195,0.226410,-0.182881,0.001031
Temperature,-0.050097,1.000000,0.143859,-0.026415,-0.179672,-0.056026,-0.050281,-0.014752,0.182112,0.096730,-0.155949,0.004437,-0.002312,0.042981,-0.058313,0.236276
Fuel_Price,0.065290,0.143859,1.000000,0.297056,0.029153,0.018615,0.166622,0.215420,-0.164210,-0.033853,-0.078281,0.003572,-0.000120,0.029687,0.003361,-0.031140
MarkDown1,-0.059844,-0.026415,0.297056,1.000000,0.174868,-0.014411,0.838904,0.415050,0.010915,-0.105168,-0.003521,0.001494,0.047172,-0.126345,0.169788,-0.093572
MarkDown2,-0.033829,-0.179672,0.029153,0.174868,1.000000,-0.006080,0.113250,0.131735,-0.003554,-0.041427,0.207604,0.000587,0.020716,-0.055318,0.078372,-0.012812
MarkDown3,-0.020331,-0.056026,0.018615,-0.014411,-0.006080,1.000000,-0.012020,0.042471,-0.005839,-0.018078,0.266471,0.001475,0.038562,-0.024013,0.033641,0.122323
MarkDown4,-0.042724,-0.050281,0.166622,0.838904,0.113250,-0.012020,1.000000,0.303370,-0.002047,-0.076513,0.011565,0.001937,0.037467,-0.089770,0.127334,-0.114168
MarkDown5,-0.012452,-0.014752,0.215420,0.415050,0.131735,0.042471,0.303370,1.000000,0.067906,-0.120406,-0.015235,0.002668,0.050465,-0.130125,0.153011,0.055737
CPI,-0.211088,0.182112,-0.164210,0.010915,-0.003554,-0.005839,-0.002047,0.067906,1.000000,-0.299953,-0.001944,-0.007477,-0.020921,-0.065812,-0.003314,0.006342
Unemployment,0.208552,0.096730,-0.033853,-0.105168,-0.041427,-0.018078,-0.076513,-0.120406,-0.299953,1.000000,0.010460,0.007837,-0.025864,0.148720,-0.068238,-0.015490
IsHoliday,-0.000548,-0.155949,-0.078281,-0.003521,0.207604,0.266471,0.011565,-0.015235,-0.001944,0.010460,1.000000,0.000916,0.012774,-0.000798,0.000593,0.128184
Dept,0.024004,0.004437,0.003572,0.001494,0.000587,0.001475,0.001937,0.002668,-0.007477,0.007837,0.000916,1.000000,0.148032,0.003708,-0.002966,0.000882
Weekly_Sales,-0.085195,-0.002312,-0.000120,0.047172,0.020716,0.038562,0.037467,0.050465,-0.020921,-0.025864,0.012774,0.148032,1.000000,-0.182242,0.243828,0.027673
Type,0.226410,0.042981,0.029687,-0.126345,-0.055318,-0.024013,-0.089770,-0.130125,-0.065812,0.148720,-0.000798,0.003708,-0.182242,1.000000,-0.811593,-0.000003
Size,-0.182881,-0.058313,0.003361,0.169788,0.078372,0.033641,0.127334,0.153011,-0.003314,-0.068238,0.000593,-0.002966,0.243828,-0.811593,1.000000,-0.001292
Week_of_year,0.001031,0.236276,-0.031140,-0.093572,-0.012812,0.122323,-0.114168,0.055737,0.006342,-0.015490,0.128184,0.000882,0.027673,-0.000003,-0.001292,1.000000

In [33]:
df_final.columns

Index(['Store', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment',
       'IsHoliday', 'Dept', 'Weekly_Sales', 'Type', 'Size', 'Week_of_year'],
      dtype='object')

In [34]:
#Hypotheses

continues=['Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
       'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment',
       'Weekly_Sales','Size', 'Week_of_year']
categories=['Store', 'IsHoliday', 'Dept', 'Type']


from scipy import stats

def two_sample(d1,d2):
  t=0
  f=0
  for i in  range(31):
    sample1=d1.sample(frac=0.03)
    sample2=d2.sample(frac=0.03)
    t_test,p_value=stats.ttest_ind(sample1,sample2)
    if p_value < 0.055:
      f=f+1
    else:
      t=t+1
  if t>f:
    return True
  else:
    return False

#defining function for categories vs categories
def chisqare_cat_vs_cat(d1,d2):
  return True if stats.chi2_contingency(pd.crosstab(d1,d2))[1] < 0.055 else False

def annova_test(d1,d2):
  group=df_final[d2].unique()
  data={}
  for i in group:
    data[i]=df_final[d1][df_final[d2]==i]
  f_value,p_value=stats.f_oneway(*[i for i in data.values()])
  if p_value < 0.055:
    return False
  else:
    return True

final={}
for i in df_final.columns:
  final[i]={}
  for j in df_final.columns:
    if (i in continues) and (j in continues):
      result=two_sample(df_final[i],df_final[j])
    elif  (i in continues) and (j in categories):
      result=annova_test(i,j)
    elif (i in categories) and (j in continues):
      result=annova_test(j,i)
    elif (i in categories) and (j in categories):
      result=chisqare_cat_vs_cat(df_final[i],df_final[j])
    if result:
      final[i][j]=1
    else:
      final[i][j]=0

/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:531: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)
/usr/local/lib/python3.11/dist-packages/scipy/stats/_axis_nan_policy.py:531: ConstantInputWarning: Each of the input arrays is constant; the F statistic is not defined or infinite
  res = hypotest_fun_out(*samples, **kwds)

In [35]:
final_Data = pd.DataFrame(final)

In [36]:
final_Data

,Store,Temperature,Fuel_Price,MarkDown1,MarkDown2,MarkDown3,MarkDown4,MarkDown5,CPI,Unemployment,IsHoliday,Dept,Weekly_Sales,Type,Size,Week_of_year
Store,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1
Temperature,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
Fuel_Price,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
MarkDown1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0
MarkDown2,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
MarkDown3,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
MarkDown4,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
MarkDown5,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0
CPI,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0
Unemployment,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
IsHoliday,0,0,0,0,0,0,0,0,1,0,1,1,0,0,1,0
Dept,1,0,0,0,0,0,0,0,0,0,1,1,0,1,0,0
Weekly_Sales,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
Type,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1
Size,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0
Week_of_year,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1

In [ ]:
for i in continues:
    print(i,df_final[i].skew(),df_final[i].kurtosis())

Temperature -0.321404151969982 -0.6359219777925134
Fuel_Price -0.1049014956284031 -1.1854045046191282
MarkDown1 4.731304105937836 34.91723635483528
MarkDown2 10.64595630692463 145.42129311587385
MarkDown3 14.92234105657218 248.09537056975668
MarkDown4 8.077666469546449 86.24233932886966
MarkDown5 9.964519133631532 183.40806548607708
CPI 0.0852192847326045 -1.8297143643268134
Unemployment 1.1837425684974345 2.7312166296417724
Weekly_Sales 3.262008185465662 21.491289908326177
Size -0.3258497664635348 -1.206345903071735
Week_of_year 0.05265944161124801 -1.111679075138652

In [ ]:
from scipy import stats
method=[0,0.5,-0.5,1,-1,2,-2]
for i in method:
      print(i)
      print("skewness",pd.DataFrame(stats.boxcox(df_final["MarkDown5"],lmbda=i)).skew().values,"kurtosis",pd.DataFrame(stats.boxcox(df_final["MarkDown5"],lmbda=i)).kurtosis().values)
print("--------------------------")

0
skewness [nan] kurtosis [nan]
0.5
skewness [1.73415401] kurtosis [4.74155757]
-0.5
skewness [nan] kurtosis [nan]
1

/usr/local/lib/python3.11/dist-packages/pandas/core/nanops.py:1256: RuntimeWarning: invalid value encountered in subtract
  adjusted = values - mean
/usr/local/lib/python3.11/dist-packages/pandas/core/nanops.py:1344: RuntimeWarning: invalid value encountered in subtract
  adjusted = values - mean

skewness [9.96451913] kurtosis [183.40806549]
-1
skewness [nan] kurtosis [nan]
2
skewness [36.42334691] kurtosis [1527.23826959]
-2
skewness [nan] kurtosis [nan]
--------------------------

In [ ]:
df_final['MarkDown5']=stats.boxcox(df_final["MarkDown5"],lmbda=-2)

In [ ]:
df_final['MarkDown5'].skew()

-13.238062633585308

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [ ]:
x=df_final.drop("Week_of_year",axis=1)
y=df_final["Week_of_year"]

In [ ]:
from tensorflow.keras.utils import to_categorical
ynew=to_categorical(y)

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,ynew,test_size=0.3)

In [ ]:
x_train_scaler=scaler.fit_transform(x_train)

In [ ]:
x_test_scaler=scaler.transform(x_test)

In [ ]:
x_train_scaler.shape[1]

15

In [ ]:
from tensorflow.keras.layers import Dense,Dropout
from tensorflow.keras.models import Sequential

import tensorflow as tf
model=Sequential()
model.add(Dense(78125,input_dim=x_train_scaler.shape[1],activation=tf.keras.layers.LeakyReLU(alpha=0.2)))
model.add(Dropout(0.2))
model.add(Dense(15625,activation=tf.keras.layers.LeakyReLU(alpha=0.2)))
model.add(Dropout(0.2))
model.add(Dense(3125,activation=tf.keras.layers.LeakyReLU(alpha=0.2)))
model.add(Dropout(0.23))
model.add(Dense(625,activation=tf.keras.layers.LeakyReLU(alpha=0.2)))
model.add(Dropout(0.15))
model.add(Dense(125,activation=tf.keras.layers.LeakyReLU(alpha=0.2)))
model.add(Dense(25,activation=tf.keras.layers.LeakyReLU(alpha=0.2)))
model.add(Dense(1))
model.compile(loss="mean_squared_error",optimizer="adam",metrics=[tf.keras.metrics.R2Score(),tf.keras.metrics.MeanAbsoluteError(),tf.keras.metrics.MeanSquaredError(),tf.keras.metrics.MeanAbsolutePercentageError()])

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_24 (Dense)                     │ (None, 1024)                │          16,384 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_12 (Dropout)                 │ (None, 1024)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 512)                 │         524,800 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_13 (Dropout)                 │ (None, 512)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_26 (Dense)                     │ (None, 256)                 │         131,328 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_14 (Dropout)                 │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (None, 64)                  │          16,448 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_28 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_29 (Dense)                     │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 691,073 (2.64 MB)

 Trainable params: 691,073 (2.64 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
x_train_scaler.shape

(295099, 15)

In [ ]:
x_test_scaler.shape

(126471, 15)

In [ ]:
result=model.fit(x_train_scaler,y_train,epochs=30,validation_data=(x_test_scaler,y_test),batch_size=15)

Epoch 1/30

AttributeError: 'NoneType' object has no attribute 'items'